#!/usr/bin/python
import os
import sys

lib_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../libs'))
sys.path.insert(0, os.path.join(here, 'myshop'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'myshop.settings'

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
# 

from django.core.handlers.wsgi import WSGIHandler
application = WSGIHandler()
